### ISSUE TITLE
Can't detect when the server has not started properly (Address/port already in use)

### ISSUE THREAD

**Issue by nicolasgarnier** [ForceUniverse/dart-forcemvc#24]
One frequent issue when starting a webserver is that the port is already in use.

Currently when that happens we get a Warning in the logs:

    WARNING: 2014-11-20 22:40:44.575: Could not startup the web server ... SocketException: Failed to create server socket (OS Error: Address already in use, errno = 48), address = 127.0.0.1, port = 7478

It wold be great to be able to catch this issue so we can take corrective measures (like restarting with a random port). For instance when doing this:

    webServer.start().catchError((e){
        //do stuff
    });

Unfortunately it doesn't seem that an Error is thrown in this case. Would be awesome if an Error of a specific type would be thrown here.

**Comment by jorishermans** [comment]
It works so we close this!
