### ISSUE TITLE
Path variables with dash

### ISSUE THREAD

**Issue by Rasarts** [ForceUniverse/dart-forcemvc#32]
Hi. I use uuid package for ids of entities and RequestMapping in Controller looks like that:
`@RequestMapping(value: '${api_uri}/entities/entity/{id}', method: 'GET')`

http request:
`http://localhost:8080/api/0.0.1/entities/entity/188575e0-d700-11e5-d18b-f130bc592bc4`

And in console I get:

> Resource not found

How i can handle uri with this uuid?

**Comment by jorishermans** [comment]
I will take a look at it and write some unittests for this issue!

**Comment by Rasarts** [comment]
Thanks.

**Comment by jorishermans** [comment]
solved in 0.8.1
